[package]
name = "trout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.11.6"
egui = "0.20.1"
clap = {version = "4.0.29", features = ["derive"]}